run:
  project_name: finetune_mpra_fewshot_multi_task
  run_name: all_genes_finetune_mpra_fewshot_multitask_stage1_no_chr_split
  use_wandb: true
type: region
stage: fit
assembly: hg38
eval_tss: true
log_image: true
model:
  _target_: get_model.model.model.GETRegionCREFinetune
  cfg:
    num_regions: 900
    num_motif: 283
    embed_dim: 768
    num_layers: 12
    num_heads: 12
    dropout: 0.1
    output_dim: 2
    multitask_output_dim: 1
    flash_attn: false
    pool_method: mean
    region_embed:
      num_regions: ${model.cfg.num_regions}
      num_features: ${model.cfg.num_motif}
      embed_dim: ${model.cfg.embed_dim}
    encoder:
      num_heads: ${model.cfg.num_heads}
      embed_dim: ${model.cfg.embed_dim}
      num_layers: ${model.cfg.num_layers}
      drop_path_rate: ${model.cfg.dropout}
      drop_rate: 0
      attn_drop_rate: 0
      use_mean_pooling: false
      flash_attn: ${model.cfg.flash_attn}
    head_exp:
      embed_dim: ${model.cfg.embed_dim}
      output_dim: ${model.cfg.output_dim}
      use_atac: false
    head_atac:
      embed_dim: ${model.cfg.embed_dim}
      output_dim: ${model.cfg.multitask_output_dim}
      use_atac: false
    head_cre:
      embed_dim: ${model.cfg.embed_dim}
      output_dim: ${model.cfg.multitask_output_dim}
      use_atac: false
    mask_token:
      embed_dim: ${model.cfg.embed_dim}
      std: 0.02
    loss:
      components:
        exp:
          _target_: torch.nn.PoissonNLLLoss
          reduction: mean
          log_input: false
        atac:
          _target_: torch.nn.MSELoss
          reduction: mean
        cre:
          _target_: torch.nn.SmoothL1Loss
          reduction: mean
      weights:
        exp: 1.0
        atac: 1.0
        cre: 1.0
    metrics:
      components:
        exp:
        - pearson
        - spearman
        - r2
        atac:
        - pearson
        - spearman
        - r2
        cre:
        - pearson
        - spearman
        - r2
    _copy_supervised_flag_: ${supervised_flag}
machine:
  codebase: /home/xf2217/Projects/get_model/
  data_path: /home/xf2217/Projects/get_data/
  output_dir: ./output
  num_devices: 1
  num_workers: 8
  batch_size: 8
  fasta_path: ???
  device_ids:
  - 0
dataset:
  zarr_path: ./oligo_cre_peaks_multiome_fewshot_multitask.zarr
  celltypes: hepg2,k562,gm12878,a549
  transform: null
  quantitative_atac: false
  sampling_step: 100
  num_region_per_sample: 200
  leave_out_chromosomes: null
  leave_out_celltypes: k562
  mask_ratio: 0.0
  cre_focus: true
  gene_focus: false
training:
  save_ckpt_freq: 1
  epochs: 50
  warmup_epochs: 1
  accumulate_grad_batches: 1
  clip_grad: null
  use_fp16: false
  log_every_n_steps: 25
  val_check_interval: 0.5
  add_lr_monitor: false
optimizer:
  lr: 0.0001
  min_lr: 0.0001
  weight_decay: 0.05
  opt: adamw
  opt_eps: 1.0e-08
  opt_betas:
  - 0.9
  - 0.999
finetune:
  resume_ckpt: null
  pretrain_checkpoint: false
  checkpoint: /home/yuzhaowei/.gcell_data/pretrain.checkpoint/checkpoint-best.pth
  strict: true
  model_key: model
  use_lora: true
  lora_checkpoint: null
  rename_config:
    blocks.: encoder.blocks.
    fc_norm.: encoder.norm.
    encoder.head.: head_mask.
    encoder.region_embed: region_embed
    region_embed.proj.: region_embed.embed.
    encoder.cls_token: cls_token
    head.: head_exp.head.
  layers_with_lora:
  - region_embed
  - encoder
  patterns_to_freeze: []
  patterns_to_drop: []
  additional_checkpoints: []
task:
  test_mode: interpret
  gene_list: null
  layer_names:
  - region_embed
  mutations: null
supervised_flag:
  supervised_exp: true
  supervised_atac: true
  supervised_cre: true
device_ids:
- 0
